version: '3'
services: 
    transferio:
        container_name: transferio_web
        build: .
        ports:
            - "5000:5000"
        volumes: 
            - ./:/app
        links: 
            - postgres
        depends_on: 
            - postgres
        restart: always
        environment: 
            DB_URI: postgres://root:transferio@postgres/transferio
    
    postgres:
        container_name: transferio_postgres
        image: postgres
        environment: 
            POSTGRES_USER: root
            POSTGRES_PASSWORD: transferio
        volumes: 
            - ./docker/init/db.sh:/docker-entrypoint-initdb.d/initdb.sh 
            - ./docker/postgres:/var/lib/postgresql/data

        restart: always
